"""mcp_config.py — Generate launcher scripts and build MCP server configurations."""

from __future__ import annotations

import os
import shlex
from pathlib import Path
from typing import Any

FLUX_ROOT = Path(__file__).resolve().parent.parent
MARKETPLACE_DIR = FLUX_ROOT / "marketplace"
MCP_DIR = MARKETPLACE_DIR / "mcps"
LAUNCHERS_DIR = MCP_DIR / "launchers"


def generate_launcher(mcp_name: str, mcp_data: dict[str, Any]) -> Path | None:
    """
    Generate a portable launcher.sh inside the MCP's own folder.
    For git-submodule MCPs: marketplace/mcps/<mcp>/launcher.sh
    For npm-package MCPs:   marketplace/mcps/<mcp>/launcher.sh (dir created if needed)
    Uses $SCRIPT_DIR so paths work on any machine.
    Returns the launcher path, or None if no keychain secrets are needed.
    """
    env_vars = mcp_data.get('auth', {}).get('env_vars', [])
    if not env_vars:
        return None

    command = mcp_data.get('command', '')
    args = list(mcp_data.get('args', []))

    # All launchers live in marketplace/mcps/launchers/ — outside submodules so
    # they can be tracked by the parent flux repo.
    launcher_dir = MCP_DIR / "launchers"
    launcher_dir.mkdir(parents=True, exist_ok=True)

    if mcp_data.get('source_dir'):
        # Compute relative path from launchers/ to the MCP source dir (e.g. ../wikijs-mcp)
        source_abs = FLUX_ROOT / mcp_data['source_dir']
        rel = os.path.relpath(source_abs, launcher_dir)
        args = [f'"$SCRIPT_DIR/{rel}"' if a == '{source_dir}' else shlex.quote(a) for a in args]
    else:
        args = [shlex.quote(a) for a in args]

    export_lines = "\n".join(
        f'export {var}=$(security find-generic-password -s flux.{mcp_name} -a {var} -w 2>/dev/null)'
        for var in env_vars
    )
    exec_line = " ".join([shlex.quote(command)] + args + ['"$@"'])

    script = f"""#!/bin/bash
# Auto-generated by flux — do not edit. Re-run 'flux sync' to regenerate.
SCRIPT_DIR="$(cd "$(dirname "${{BASH_SOURCE[0]}}")" && pwd)"
{export_lines}
exec {exec_line}
"""
    launcher_path = launcher_dir / f"{mcp_name}.sh"
    launcher_path.write_text(script)
    launcher_path.chmod(0o755)
    return launcher_path


def build_mcp_server_config(
    mcp_name: str, mcp_data: dict[str, Any], extra_args: list[str] | None = None,
) -> dict[str, Any]:
    """Build .mcp.json server entry. Uses a launcher script for keychain secrets."""
    env_vars = mcp_data.get('auth', {}).get('env_vars', [])

    if env_vars:
        # Generate launcher that fetches secrets from Keychain at runtime
        launcher = generate_launcher(mcp_name, mcp_data)
        server = {"command": str(launcher), "args": extra_args or []}
    else:
        server = {k: v for k, v in mcp_data.items() if k in ['command', 'args', 'env']}
        if extra_args:
            server['args'] = server.get('args', []) + extra_args
        # Resolve {source_dir} placeholder to absolute path
        if mcp_data.get('source_dir'):
            abs_source = str(FLUX_ROOT / mcp_data['source_dir'])
            server['args'] = [abs_source if a == '{source_dir}' else a for a in server.get('args', [])]

    return server


def enrich_with_marketplace(servers: dict[str, Any], mcp_registry: dict[str, Any]) -> dict[str, Any]:
    """Merge marketplace auth metadata into server configs from .mcp.json."""
    enriched = {}
    for name, config in servers.items():
        merged = dict(config)
        if name in mcp_registry:
            for k, v in mcp_registry[name].items():
                if k not in merged:
                    merged[k] = v
        enriched[name] = merged
    return enriched
