"""Sync engine — read flux.json + registry, generate .mcp.json and launcher scripts."""

from __future__ import annotations

import json
import platform
import re
import shlex
import tempfile
from pathlib import Path
from typing import Any

from flux_cli.paths import flux_home, launchers_dir, registry_path, skills_dir

_SAFE_NAME_RE = re.compile(r"^[a-zA-Z0-9][a-zA-Z0-9_-]*$")
_SAFE_ENV_VAR_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")

# ---------------------------------------------------------------------------
# Registry helpers
# ---------------------------------------------------------------------------


def _load_registry_for_sync(reg_path: Path | None = None) -> dict[str, Any]:
    """Load the v1 registry for sync operations."""
    path = reg_path or registry_path()
    if not path.exists():
        return {"version": "1.0.0", "mcp_definitions": {}, "skill_definitions": {}}
    with open(path) as f:
        return json.load(f)


# ---------------------------------------------------------------------------
# Launcher script generation
# ---------------------------------------------------------------------------


def _secret_lookup_command(mcp_name: str, var: str) -> str:
    """Return a platform-specific shell command to fetch a secret at runtime."""
    if not _SAFE_NAME_RE.match(mcp_name):
        msg = f"Unsafe MCP name for shell embedding: {mcp_name!r}"
        raise ValueError(msg)
    if not _SAFE_ENV_VAR_RE.match(var):
        msg = f"Unsafe env var name for shell embedding: {var!r}"
        raise ValueError(msg)

    if platform.system() == "Darwin":
        return (
            f"$(security find-generic-password -s flux.{mcp_name} -a {var} -w 2>/dev/null)"
        )
    return (
        f"$(secret-tool lookup service flux.{mcp_name} username {var} 2>/dev/null)"
    )


def generate_launcher(
    mcp_name: str,
    mcp_data: dict[str, Any],
    *,
    launcher_base: Path | None = None,
) -> Path | None:
    """Generate a platform-aware launcher script for an authed MCP."""
    env_vars = mcp_data.get("auth", {}).get("env_vars", [])
    if not env_vars:
        return None

    launcher_base = launcher_base or launchers_dir()
    launcher_base.mkdir(parents=True, exist_ok=True)

    command = mcp_data.get("command", "")
    args = list(mcp_data.get("args", []))

    if mcp_data.get("source_dir"):
        import os

        source_abs = Path(mcp_data["source_dir"])
        if not source_abs.is_absolute():
            source_abs = flux_home().parent / mcp_data["source_dir"]
        rel = os.path.relpath(source_abs, launcher_base)
        args = [
            f'"$SCRIPT_DIR/{rel}"' if a == "{source_dir}" else shlex.quote(a)
            for a in args
        ]
    else:
        args = [shlex.quote(a) for a in args]

    export_lines = "\n".join(
        f"export {var}={_secret_lookup_command(mcp_name, var)}" for var in env_vars
    )
    exec_line = " ".join([shlex.quote(command)] + args + ['"$@"'])

    script = f"""#!/bin/bash
# Auto-generated by flux sync — do not edit. Re-run 'flux sync' to regenerate.
SCRIPT_DIR="$(cd "$(dirname "${{BASH_SOURCE[0]}}")" && pwd)"
{export_lines}
exec {exec_line}
"""
    safe_name = Path(mcp_name).name
    launcher_path = launcher_base / f"{safe_name}.sh"
    launcher_path.write_text(script)
    launcher_path.chmod(0o700)
    return launcher_path


# ---------------------------------------------------------------------------
# .mcp.json generation
# ---------------------------------------------------------------------------


def _build_server_entry(
    mcp_name: str,
    mcp_data: dict[str, Any],
    extra_args: list[str] | None = None,
    *,
    launcher_base: Path | None = None,
) -> dict[str, Any]:
    """Build a single mcpServers entry for .mcp.json."""
    env_vars = mcp_data.get("auth", {}).get("env_vars", [])

    if env_vars:
        launcher = generate_launcher(mcp_name, mcp_data, launcher_base=launcher_base)
        return {"command": str(launcher), "args": extra_args or []}

    server: dict[str, Any] = {
        k: v for k, v in mcp_data.items() if k in ("command", "args", "env")
    }
    if extra_args:
        server["args"] = server.get("args", []) + extra_args

    if mcp_data.get("source_dir"):
        abs_source = mcp_data["source_dir"]
        if not Path(abs_source).is_absolute():
            abs_source = str(flux_home().parent / abs_source)
        server["args"] = [
            abs_source if a == "{source_dir}" else a for a in server.get("args", [])
        ]

    return server


def sync_project(
    project_dir: Path,
    registry: dict[str, Any] | None = None,
    *,
    launcher_base: Path | None = None,
) -> tuple[bool, list[str]]:
    """Sync a single project: generate .mcp.json, copy skills."""
    flux_json_path = project_dir / "flux.json"
    if not flux_json_path.exists():
        return False, ["No flux.json found"]

    with open(flux_json_path) as f:
        flux_json = json.load(f)

    if registry is None:
        registry = _load_registry_for_sync()

    mcp_defs = registry.get("mcp_definitions", {})
    skill_defs = registry.get("skill_definitions", {})
    issues: list[str] = []

    # Build .mcp.json
    declared_mcps = flux_json.get("mcps", [])
    mcp_servers: dict[str, Any] = {}
    for mcp_entry in declared_mcps:
        if isinstance(mcp_entry, str):
            mcp_name, extra_args = mcp_entry, []
        else:
            mcp_name = mcp_entry.get("name", "")
            extra_args = mcp_entry.get("args", [])
        if mcp_name not in mcp_defs:
            issues.append(f"MCP '{mcp_name}' not found in registry")
            continue
        mcp_servers[mcp_name] = _build_server_entry(
            mcp_name, mcp_defs[mcp_name], extra_args or None, launcher_base=launcher_base
        )

    mcp_file = project_dir / ".mcp.json"
    new_config = {"mcpServers": mcp_servers}
    _atomic_json_write(mcp_file, new_config)

    # Copy skills
    declared_skills = flux_json.get("skills", [])
    for skill_name in declared_skills:
        if skill_name not in skill_defs:
            issues.append(f"Skill '{skill_name}' not found in registry")
            continue
        skill_data = skill_defs[skill_name]
        source_dir_str = skill_data.get("source_dir", "")
        source_path = Path(source_dir_str)
        if not source_path.is_absolute():
            candidate = skills_dir() / skill_name
            if candidate.exists():
                source_path = candidate
            elif source_dir_str:
                source_path = flux_home().parent / source_dir_str
            else:
                source_path = skills_dir() / skill_name

        safe_skill = Path(skill_name).name
        skills_parent = project_dir / ".claude" / "skills"
        dest_path = skills_parent / safe_skill
        if source_path.exists():
            import shutil

            if not dest_path.resolve().is_relative_to(skills_parent.resolve()):
                issues.append(f"Skill '{skill_name}' resolves outside skills directory")
                continue
            dest_path.parent.mkdir(parents=True, exist_ok=True)
            if dest_path.exists():
                shutil.rmtree(dest_path)
            shutil.copytree(source_path, dest_path)
        else:
            issues.append(f"Skill '{skill_name}' source missing at {source_path}")

    return True, issues


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _atomic_json_write(path: Path, data: dict[str, Any]) -> None:
    """Write JSON atomically."""
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(dir=path.parent, suffix=".tmp")
    try:
        with open(fd, "w") as f:
            json.dump(data, f, indent=2)
        Path(tmp).replace(path)
    except BaseException:
        Path(tmp).unlink(missing_ok=True)
        raise
